config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
    get '/users/:id', to: 'users#show'

  resources :users
  resources :neighborhoods do
    resources :incidents
  end

  root to: 'users#index'


end

app/models/incident.rb
class Incident < ApplicationRecord
  extend ::Geocoder::Model::ActiveRecord

belongs_to :neighborhood

  validates_presence_of :date, :description, :address

  geocoded_by :address
  before_save :geocode

  def image_url
    case description
    when "theft"
      "https://cdn2.iconfinder.com/data/icons/snipicons/500/map-marker-128.png"
    when "whatever"
      "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png"
    else
      "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png"
    end
  end
end

app/controllers/incidents_controller.rb
class IncidentsController < ApplicationController
  before_action :load_neighborhood
  before_action :set_incident, only: [:show, :edit, :update, :destroy]

  # GET /incidents
  # GET /incidents.json
  def index
    if params[:search].present?
      @incidents = Incident.near(params[:search], 50, :order => :distance)
    else
      @incidents = @neighborhood.incidents.all
    end
  end

  # GET /incidents/1
  # GET /incidents/1.json
  def show
  end

  # GET /incidents/new
  def new
    @incident = Incident.new
  end

  # GET /incidents/1/edit
  def edit
  end

  # POST /incidents
  # POST /incidents.json
  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @incident = @neighborhood.incidents.new(incident_params)

    respond_to do |format|
      if @incident.save!
        format.html { redirect_to neighborhood_incidents_path(@neighborhood, @incidents), notice: 'Incident was successfully created.' }
        format.json { render :show, status: :created, location: @incident }
      else
        format.html { render :new }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /incidents/1
  # PATCH/PUT /incidents/1.json
  def update
    respond_to do |format|
      if @incident.update(incident_params)
        format.html { redirect_to neighborhood_incidents_path(@neighborhood, @incidents), notice: 'Incident was successfully updated.' }
        format.json { render :show, status: :ok, location: @incident }
      else
        format.html { render :edit }
        format.json { render json: @incident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /incidents/1
  # DELETE /incidents/1.json
  def destroy
    @incident.destroy
    respond_to do |format|
      format.html { redirect_to neighborhood_incidents_path(@neighborhood), notice: 'Incident was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_neighborhood
      @neighborhood = Neighborhood.find(params[:neighborhood_id])
    end

    def set_incident
      @incident = Incident.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def incident_params
      params.require(:incident).permit(:address, :latitude, :longitude, :date, :description)
    end
end

app/helpers/incidents_helper.rb
module IncidentsHelper
end

app/views/incidents/_form.html.erb
<%= form_for [@neighborhood, @incident] do |f| %>
  <%
  if @incident.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@incident.errors.count, "error") %> prohibited this incident from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @incident.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="form-group">
    <%= f.label :date, :class => 'control-label col-md-2' %>
      <%= f.text_field :date, :class => 'form-control' %>
    <%=f.error_span(:date) %>
  </div>


    <div class="form-group">
        <%= f.label :address, :class => 'control-label col-lg-2' %>
        <%= f.text_field :address, :class => 'form-control' %>
      <%=f.error_span(:address) %>
    </div>

  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
      <%= f.text_field :description, :class => 'form-control' %>
    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                neighborhood_incidents_path(@neighborhood), :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/incidents/edit.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/incidents/index.html.erb
<div class= 'container'>
  <div row= 'row'>
    <div class="col-md-12">
    <%- model_class = Neighborhood -%>

    <div class="panel panel-default">
      <div class="panel-body">
      <%= @neighborhood.name %>
      <%= @neighborhood.city + ', '%>
      <%= @neighborhood.state %>
      </div>
    </div>
    </div>
  </div>
</div>

  <div class= 'container'>
    <div row= 'row'>
      <div class="col-md-6">
        <%- model_class = Incident -%>

          <h3><%= "Incidents" %></h3>
          <div>  <%= link_to t('.new', :default => t("helpers.links.new")), new_neighborhood_incident_path(@neighborhood),
                                  :class => 'btn btn-default btn-xs pull-right', :span =>  'glyphicon glyphicon-star' %>
          </div>

        <table class="table table-striped">
        <thead>
          <tr>
          <th><%= model_class.human_attribute_name(:date) %></th>
          <th><%= model_class.human_attribute_name(:address) %></th>
          <th><%= model_class.human_attribute_name(:description) %></th>

    </tr>
  </thead>
  <tbody>
    <% @incidents.each do |incident| %>
      <tr>
        <td><%= link_to incident.date, neighborhood_incident_path(@neighborhood, incident.date) %></td>
        <td><%= link_to incident.address, neighborhood_incident_path(@neighborhood, incident.address) %></td>
        <td><%= incident.description %></td>

        <td>
          <% if user_signed_in? && current_user == incident.neighborhood.user %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_neighborhood_incident_path(@neighborhood, incident), :class => 'btn btn-default btn-xs' %>

                      <li><%= link_to current_user.email, edit_user_registration_path %></li>
                      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete  %></li>
            <% end %>
                      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      neighborhood_incident_path(@neighborhood, incident),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs <btn-default></btn-default>' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>

  <div class="col-md-6">

    <div id="map-container" style="height:400px; border-radius: 16px 16px; border-color: #fff;
    border-style: solid; box-shadow: 2px 2px 10px #B1B1B1; margin-top: 25px; border-width: 7px;">
    <div id="map" style="height: 384px; width:100%">
    </div>
  </div>
  </div>
</div>

<script>

   handler = Gmaps.build('Google');
   handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
     <% @incidents.each do |incident| %>
      {
        lat: <%= incident.latitude %>,
        lng: <%= incident.longitude %>,
        picture: {
          url: "<%= incident.image_url %>",
          width:  36,
          height: 36
        }
      },
    <% end %>
   ]);

   handler.bounds.extendWith(markers);
   handler.fitMapToBounds();
   });

</script>

app/views/incidents/new.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form', :user => @user, :neighborhood => @neighborhood, :incident => @incident %>

app/views/incidents/show.html.erb
<%- model_class = Incident -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class='container'>
  <div class='row'>
  <div class="col-md-6">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:date) %>:</strong></dt>
  <dd><%= @incident.date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @incident.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @incident.description %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              neighborhood_incidents_path(@neighborhood), :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_neighborhood_incident_path(@neighborhood, @incident), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              neighborhood_incident_path(@incident),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

</div>

        <div class="col-md-6">
           <div class="map-container" style="height:400px; border-radius: 16px 16px; border-color: #fff;
              border-style: solid; box-shadow: 2px 2px 10px #B1B1B1; margin-top: 25px; border-width: 7px;">

              <div id="map" style="height: 384px; width:100%"> </div>
          </div>
      </div>
    </div>
  </div>

<script>

handler = Gmaps.build('Google');
handler.buildMap({ provider: { disableDefaultUI: true}, internal: {id: 'map'}}, function(){
  markers = handler.addMarkers([
       {
         lat: <%= @incident.latitude %>,
         lng: <%= @incident.longitude %>,
         picture: {
                 url: "https://cdn2.iconfinder.com/data/icons/snipicons/500/map-marker-128.png",
                 width:  70,
                 height: 70
               }

        }
       ]);
  handler.bounds.extendWith(markers);
  handler.fitMapToBounds();
  });

</script>