config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
    get '/users/:id', to: 'users#show'

  resources :users
  resources :neighborhoods do
    resources :incidents
  end

  root to: 'users#index'


end

app/models/user.rb
class User < ApplicationRecord
  extend ::Geocoder::Model::ActiveRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :neighborhood, required: false

  geocoded_by :address
  before_save :geocode

     #def address
      # "#{street}#{city}#{state}"
     #end

  end

app/controllers/User/confirmations_controller.rb
class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
before_action :load_user, only: [ :edit, :show, :update]
before_action :authenticate_user!
#before_action :get_neighborhood, only: [:create]


  # GET /resource/sign_up
  def new
     super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end
  def create
    #@user = User.create(street: "whetaver", city: "City", State: "State", postal_code: "Postal Code", neighboorhood: "Wagener")
    #@location = Location.find_or_create_by(params[:address])@user = User.new(user_params)
    super
    #@user = User.new(user_params)

    if @user.save!
      @lat = @user[:latitude]
      @lon = @user[:longitude]
      neighborhood = get_neighborhood
      neighborhood_id = Neighborhood.find_by(name: neighborhood)[:id]
      @user.update_attribute(:neighborhood_id, neighborhood_id)
      # redirect_to neighborhood_incidents_path(neighborhood_id, @incidents), notice:"Great! We found your neighborhood!"
    else
    render new, notice:"Oops, something went wr ong! Try again!"
    end
  end

  def update
    if params[:address].present?
     @user = User.geolocate(params[:address])
    respond_to do |format|
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully created.'
    else
      flash[:error]  = "Oops! We couldn't update the user, please review the errors"
      render :edit
    end
    end
  end
end
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :address, :first_name, :last_name, :state, :city, :street, :neighborhood_id, :latitude, :longitude])
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(user)
    super(user)
      if user.neighborhood
        neighborhood_incidents_path(user.neighborhood)
      else
        edit_user_path(user)
      end
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  private

    def load_user
      @user = User.find(params[:id])
    end

    def get_neighborhood
      require 'http'
      url = URI.parse("https://maps.googleapis.com/maps/api/geocode/json?latlng=#{@lat},#{@lon}&key=AIzaSyDYx7xwDQTH_giQcHYjPKS1pK0CpHSplug")
      res = HTTP.get(url)
      data = JSON.parse(res.body)
      #byebug
      data['results'][0]['address_components'].each do |c|
        if c['types'][0] == 'neighborhood'
          return c['long_name']
        else
          # do something
        end
      end
    end


    def user_params
      params.require(:user).permit(:street, :city, :state, :address, :neighborhood_id, :latitude, :longitude, :first_name, :last_name)
    end

end

app/controllers/User/sessions_controller.rb
class User::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [ :edit, :create, :show, :update]
  before_action :authenticate_user!
  before_action :get_neighborhood, only: [:create]


    def index
        @users = User.all
      end

    def new
      @user = User.new
    end

    def edit
    end

    # def create
    #   #@user = User.create(street: "whetaver", city: "City", State: "State", postal_code: "Postal Code", neighboorhood: "Wagener")
    #   #@location = Location.find_or_create_by(params[:address])@user = User.new(user_params)
    #   @user = User.new(user_params)
    #   neighborhood = get_neighborhood(user_params[:latitude],user_params[:longitude])
    #   neighborhood_id = 2 #Neighborhood.find_by(name: neighborhood)[:id]
    #
    #   if @user.save!
    #   binding.pry
    #   @user.update_attribute(:neighborhood_id, neighborhood_id)
    #   redirect_to neighborhood_incidents_path(neighborhood_id, @incidents), notice:"Great! Now let's find your neighborhood!"
    #   else
    #   render new, notice:"Oops, something went wr ong! Try again!"
    #   end
    # end

    def update
      if params[:address].present?
       @user = User.geolocate(params[:address])
      respond_to do |format|
      if @user.update(user_params)
        redirect_to @user, notice: 'User was successfully created.'
      else
        flash[:error]  = "Oops! We couldn't update the user, please review the errors"
        render :edit
      end
      end
    end
  end

    def show
    end

private

  def load_user
    @user = User.find(params[:id])
  end
  #
  # def get_neighborhood(lat, lon)
  #   require 'http'
  #
  #   url = URI.parse("https://maps.googleapis.com/maps/api/geocode/json?latlng=#{lat},#{lon}&key=AIzaSyDYx7xwDQTH_giQcHYjPKS1pK0CpHSplug")
  #   res = HTTP.get(url)
  #   data = JSON.parse(res.body)
  #   data['results'][0]['address_components'].each do |component|
  #     if component['types'][0] == 'neighborhood'
  #       return component["long_name"]
  #     else
  #       return 'not_found'
  #     end
  #   end
  # end


  def user_params
    params.require(:user).permit(:street, :city, :state, :address, :neighborhood_id, :latitude, :longitude, :first_name, :last_name)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="field">
<%= form_tag @user, :method => :get do  %>
<p>
<%= text_field_tag :address => params[:address]  %>
<%= submit_tag "Search", :name => nil %>
</p>





<% end %>

app/views/users/edit.html.erb
  <div class="field">
<%= form_tag @user, :method => :get do  %>
<p>
  <%= text_field_tag :address => params[:address]  %>
  <%= submit_tag "Search", :name => nil %>
</p>



<% end %>

app/views/users/edit0.html.erb
<%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :street %><br />
      <%= f.text_field :street, autofocus: true %>
    </div>
    <div class="field">
      <%= f.label :city %><br />
      <%= f.text_field :city, autofocus: true  %>
    </div>
    <div class="field">
        <%= f.label :state %><br />
        <%= f.text_field :state, autofocus: true  %>
    </div>
    <div class="field">
        <%= f.label :address %><br />
        <%= f.text_field :address, autofocus: true  %>
    </div>
    <div class="actions">
      <%= f.submit "Submit" %>
    </div>
  <% end %>


  <div id="floating-panel">
    <input id="address" type="textbox" value="">
    <input id="submit" type="button" value="Find Neighborhood">
  </div>
  <div id="map"></div>

  <script>

    function initMap() {
      var map = new google.maps.Map(document.getElementById('map'), {
        zoom: 8,
        center: {lat: -34.397, lng: 150.644}
      });

      var geocoder = new google.maps.Geocoder();

        document.getElementById('submit').addEventListener('click', function() {
          geocodeAddress(geocoder, map);


     })


    function geocodeAddress(geocoder, resultsMap) {
      var address = document.getElementById('address').value;

      geocoder.geocode({'address': address}, function(results, status) {
        if (status === 'OK') {
          resultsMap.setCenter(results[0].geometry.location);

          var marker = new google.maps.Marker({
            map: resultsMap,
            position: results[0].geometry.location
        });

          var lat = results[0].geometry.location.lat();
          var lng = results[0].geometry.location.lng();
          var hood = results[0].address_components[0].types[0];
        console.log(lat, lng, hood);

        } else {
          alert('Geocode was not successful for the following reason: ' + status);
        }
      })
    }
  }
  </script>

      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDYx7xwDQTH_giQcHYjPKS1pK0CpHSplug&callback=initMap"
          async defer></script>

app/views/users/index.html.erb
<%= 'User Home Page' %>
<div class= "jumbotron">

  <%= form_tag users_path, :method => :get do  %>
  <p>
    <%= text_field_tag :address => params[:address]  %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <% end %>

  <table>
    <tr>
      <th> Neighborhood</th>
      <th> Address</th>
      <th> Latitude</th>
      <th> Longitude</th>
</tr>
  <% @users.each do |user| %>
  <td>user.first_name</td>
  <td>user.last_name</td>
  <td>user.neighboorhood</td>
  <td><%= link_to "Show", user %></td>
  <td><%= link_to "Edit", edit_user_path(user) %></td>
  <td><%= link_to "Destory", user, :confirm => "Are you sure?", :method => :delete %></td>
</tr>
<% end %>
</table>
</div>
 <p><%= link_to "New Location", new_neighborhood_path %></p>

 <script>

    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers([
      <% @users.each do |user| %>
       {
         lat: <%= user.latitude %>,
         lng: <%= user.longitude %>,

       },
     <% end %>
    ]);

    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });

 </script>

app/views/users/new.html.erb
<h2>Sign up users/new</h2>

<%= form_for @user do |f| %>

    <div class="field">
      <%= f.label :address %><br/>
      <%= f.text_field :address, autofocus: true  %>
    </div>

  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.email_field :latitude, autofocus: true %>
  </div>

    <div class="field">
      <%= f.label :longitude %><br />
      <%= f.email_field :longitude, autofocus: true %>
    </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>

<% end %>

app/views/users/show.html.erb
<header>
  <h1 class="display-4">
    <%= "Welcome, " + @user.first_name.to_s + @user.last_name.to_s + "!" %> </h1>
</header>

<div class= "jumbotron">
<p> <strong> Neighborhood: </strong>
  <%= @user.address %>
</p>

<p> <strong> Address: </strong>
  <%= @user.street.to_s + @user.city.to_s + @user.state.to_s %>
</p>

<p> <strong> Latitude: </strong>
  <%= @user.latitude %>
</p>

<p> <strong> longitude: </strong>
  <%= @user.longitude %>
</p>
</div>

<div class="col-md-6">
<div id="map-container" style="height:400px; border-radius: 16px 16px; border-color: #fff;
border-style: solid; box-shadow: 2px 2px 10px #B1B1B1; margin-top: 25px; border-width: 7px;">
 <div id="map" style="height: 384px; width:100%">


</div>
</div>
</div>

<script>

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: { disableDefaultUI: true}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
        {
          lat: <%= @user.latitude %>,
          lng: <%= @user.longitude %>,
          picture: {
                  url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                  width:  36,
                  height: 36
                }

         }
        ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });


</script>