config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'user/registrations'
  }
    get '/users/:id', to: 'users#show'

  resources :users
  resources :neighborhoods do
    resources :incidents
  end

  root to: 'users#index'


end

app/models/neighborhood.rb
class Neighborhood < ApplicationRecord
  extend ::Geocoder::Model::ActiveRecord

  has_many :incidents

  validates_presence_of :name, :city, :state

belongs_to :user

  geocoded_by :address
  before_save :geocode

  def address
    "#{name} #{city} #{state}"
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_neighborhood, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :owns_neighborhood, only: [ :edit, :update, :destroy]

  # GET /neighborhoods.json
  def index
    @neighborhoods = Neighborhood.all
  end

  # GET /neighborhoods/1
  # GET /neighborhoods/1.json
  def show
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
  end

  # GET /neighborhoods/1/edit
  def edit
  end

  # POST /neighborhoods
  # POST /neighborhoods.json
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)
    @neighborhood.user = current_user
    respond_to do |format|
      if @neighborhood.save
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully created.' }
        format.json { render :show, status: :created, location: @neighborhood }
      else
        format.html { render :new }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  # PATCH/PUT /neighborhoods/1.json
  def update
    respond_to do |format|
      if @neighborhood.update(neighborhood_params)
        format.html { redirect_to @neighborhood, notice: 'Neighborhood was successfully updated.' }
        format.json { render :show, status: :ok, location: @neighborhood }
      else
        format.html { render :edit }
        format.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  # DELETE /neighborhoods/1.json
  def destroy
    @neighborhood.destroy
    respond_to do |format|
      format.html { redirect_to neighborhoods_url, notice: 'Neighborhood was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def owns_neighborhood
      if !user_signed_in? || current_user != Neighborhood.find(params[:id]).user
        redirect_to neighborhoods_path, error: "You can't do that!"
      end
    end

    def set_neighborhood
      @neighborhood = Neighborhood.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :city, :state)
    end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper

end

app/views/neighborhoods/_form.html.erb
<%= form_for @neighborhood, :html => { :class => "form-horizontal neighborhood" } do |f| %>

  <% if @neighborhood.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@neighborhood.errors.count, "error") %> prohibited this neighborhood from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @neighborhood.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div>
  <div class="form-group">
    <%= f.label :city, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :city, :class => 'form-control' %>
    </div>
    <%=f.error_span(:city) %>
  </div>
  <div class="form-group">
    <%= f.label :state, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :state, :class => 'form-control' %>
    </div>
    <%=f.error_span(:state) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                neighborhoods_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/neighborhoods/_video.html.erb
<iframe width="490" height="275" src="<%= url %>" frameborder="0" allowfullscreen></iframe>

app/views/neighborhoods/edit.html.erb
<h1>Editing Neighborhood</h1>

<%= render 'form', neighborhood: @neighborhood %>

<%= link_to 'Show', @neighborhood %> |
<%= link_to 'Back', neighborhoods_path %>

app/views/neighborhoods/home.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:city) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @neighborhoods.each do |neighborhood| %>
      <tr>
        <td><%= link_to neighborhood.id, neighborhood_path(neighborhood) %></td>
        <td><%= neighborhood.name %></td>
        <td><%= neighborhood.city %></td>
        <td><%= neighborhood.state %></td>
        <td><%=l neighborhood.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_neighborhood_path(neighborhood), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      neighborhood_path(neighborhood),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_neighborhood_path,
            :class => 'btn btn-primary' %>

app/views/neighborhoods/index.html.erb
    <div class="container">
      <div class="row">
        <div class= "col-md-8">
          <video width="600" height="500" autoplay="true">
            <source src="<%= video_path("mapVideo.mp4") %>" type="video/mp4">
            </video>
        </div>

      <div class= "col-md-4">
        <h2>Log in</h2>

        <%= form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
          <div class="field">
            <%= f.label :email%><br />
            <%= f.email_field :email, autofocus: true, placeholder: "name@gmail.com"%>
          </div>

          <div class="field">
            <%= f.label :password %><br />
            <%= f.password_field :password, autocomplete: "off" %>
          </div>

          <div class="actions">
            <%= f.submit "Log in" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="neighborhood-guides">
<div class="container">
<div class="row">
   <div class="col-md-4">
        <div class="thumbnail">
        <img src="https://d2i1pl9gz4hwa7.cloudfront.net/T1yq4UXa4HR_COFEAkCA7A"></div>
    </div>

<div class="col-md-4">
    <div class="thumbnail">

       <img src="https://i.imgur.com/mM82YXg.png">
     </div>
</div>

<div class="col-md-4">
     <div class="thumbnail">

      <img src="https://www.woopra.com/wp-content/uploads/2014/10/anonymous-profile.png">
    </div>
</div>

</div>
</div>
</div>


  <div class="container">

      <div class="col-md-4">
      <h3>Live Blotter</h3>
      <p>Report crimes. <br> Report Suspicious Activity.</p>
      <p><a href="#">See how</a></p>
    </div>
      <div class="col-md-4">
      <h3>Map of Incidents</h3>
      <p>See reported crimes and suspicious activity happening in your neighborhood.</p>
      <p><a href="#">See more</a></p>
  </div>
      <div class="col-md-4">
      <h3>Trust the community</h3>
      <p>Only Verified community members can report activity.</p>
      <p><a href="#">Learn more</a></p>
  </div>
  </div>
</div>
</div>

</body>
</html>

</div>
</div>
</div>

app/views/neighborhoods/new.html.erb
<%- model_class = Neighborhood -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/neighborhoods/show.html.erb
<div class='container'>
  <div class = 'row'>
    <div class = 'col-md-6'>
        <%- model_class = Neighborhood -%>
        <div class="page-header">
          <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1> </div>

    <div class="jumbotron">
      <div><%= model_class.human_attribute_name(:name) %>
      <%= @neighborhood.name %></div>
      <div><%= model_class.human_attribute_name(:city) %>
        <%= @neighborhood.city %>
      </div>
      <div><%= model_class.human_attribute_name(:state) %>
        <%= @neighborhood.state %>
      </div>
      <div><%= model_class.human_attribute_name(:latitude) %>
        <%= @neighborhood.latitude %>
      </div>
      <div><%= model_class.human_attribute_name(:longitude) %>
        <%= @neighborhood.longitude %>
      </div>
  </div>

          <%= link_to t('.back', :default => t("helpers.links.back")),
                        neighborhoods_path, :class => 'btn btn-default'  %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_neighborhood_path(@neighborhood), :class => 'btn btn-default' %>

  </div>

    <div class="col-md-6">
     <div class="map-container" style="height:400px; border-radius: 16px 16px; border-color: #fff;
        border-style: solid; box-shadow: 2px 2px 10px #B1B1B1; margin-top: 25px; border-width: 7px;">

        <div id="map" style="height: 384px; width:100%"> </div>
    </div>
    </div>
  </div>
</div>


<script>

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: { disableDefaultUI: true}, internal: {id: 'map'}}, function(){
   markers = handler.addMarkers([
        {
          lat: <%= @neighborhood.latitude %>,
          lng: <%= @neighborhood.longitude %>,
          picture: {
                  url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
                  width:  36,
                  height: 36
                }

         }
        ]);
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });


</script>